### ISSUE TITLE
Recommends of perl 5.20 causes issues with CPAN.pm

### ISSUE THREAD

**Issue by haarg** [sanko/readonly#16]
CPAN.pm by default installs recommends, but it ends up treating them like normal prerequisites.  When a module recommends a higher version of perl, it decides it can't install the module at all and aborts.  This of course isn't how it should behave, but it is the current state.

Given that there's nothing useful an installer could do with a recommendation of a higher perl version, the recommendation should really just be removed.

**Comment by sanko** [comment]
Shouldn't this be reported as a bug in CPAN.pm? At least until the documentation of recommends vs. requires changes, that is...

**Comment by haarg** [comment]
It has been reported as an issue on CPAN.pm (andk/cpanpm#73). It has not yet been fixed. Even if it had been though, there are tons of systems out in the wild that have this issue. And as mentioned, the current recommendation serves no useful purpose.

**Comment by Grinnz** [comment]
'requires' of a perl version is not a dependency that can be fulfilled, it is only a dependency that can abort an installation early (One might argue that it's an inconsistent usage of the 'prereqs' metadata, but that's a different conversation and it works well enough as it is, with everything special-casing it already). Along that line, 'recommends' of a perl version is completely pointless, except for documentation purposes, which is better served by documentation. Since CPAN.pm will always have this bug on older versions of perl, it's not beneficial and actively detrimental to include a recommends on perl.

**Comment by sanko** [comment]
Fine. Here comes v2.03

**Comment by karenetheridge** [comment]
many toolchain minions thank you :) 👯 👯
